version: '3.8'

services:
  # -------------------------------------------------------------------
  # Apache Airflow Orchestrator (Điều phối luồng DAG D-1 / Real-time Batch)
  # -------------------------------------------------------------------
  airflow-standalone:
    image: apache/airflow:2.8.1-python3.10
    container_name: airflow_orchestrator
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=logistics_secret_key
    ports:
      - "8085:8080"
    command: standalone
