-- ====================================================================
-- Oracle 23ai Free Setup for Debezium CDC LogMiner
-- ====================================================================

-- 1. Bật ARCHIVELOG mode và Supplemental Logging toàn cục
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE OPEN;


-- 3. Tạo service alias ORCLCDB trỏ về root container
BEGIN
    DBMS_SERVICE.CREATE_SERVICE('ORCLCDB', 'ORCLCDB');
    DBMS_SERVICE.START_SERVICE('ORCLCDB');
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- 4. Cấp quyền LogMiner CDC cho user c##dbzuser
ALTER SESSION SET CONTAINER = CDB$ROOT;
CREATE USER c##dbzuser IDENTIFIED BY dbz CONTAINER=ALL;
GRANT CREATE SESSION, ALTER SESSION, SET CONTAINER, SELECT ANY DICTIONARY, FLASHBACK ANY TABLE, SELECT ANY TABLE, SELECT ANY TRANSACTION TO c##dbzuser CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR TO c##dbzuser CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO c##dbzuser CONTAINER=ALL;
GRANT LOGMINING TO c##dbzuser CONTAINER=ALL;

-- 5. Tạo User/Schema DEBEZIUM trong PDB FREEPDB1
ALTER SESSION SET CONTAINER = FREEPDB1;
CREATE USER debezium IDENTIFIED BY dbz;
GRANT CONNECT, RESOURCE, DBA TO debezium;
GRANT UNLIMITED TABLESPACE TO debezium;
