dbt_warehouse_clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      driver: http
      host: clickhouse_server
      port: 8123
      user: default
      password: ""
      schema: default
